# Generated by Django 2.0 on 2017-12-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cpf', models.TextField()),
                ('login', models.TextField()),
                ('chave', models.TextField()),
                ('data_cadastro', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('fantasia', models.TextField()),
                ('cnpj', models.TextField()),
                ('banco_codigo', models.TextField()),
                ('banco_agencia', models.TextField()),
                ('banco_conta', models.TextField()),
                ('banco_tipo', models.TextField()),
                ('data_cadastro', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.BigIntegerField()),
                ('data_pregao', models.BigIntegerField()),
                ('numero_nota', models.BigIntegerField()),
                ('valor_negocio', models.FloatField()),
                ('valor_taxa_operacional', models.FloatField()),
                ('valor_taxa_registro_bmf', models.FloatField()),
                ('valor_taxa_emolumento_bmf', models.FloatField()),
                ('valor_iss', models.FloatField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ir.Cliente')),
                ('id_corretora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ir.Corretora')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('percentual_bmf', models.FloatField()),
                ('percentual_ir', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='lancamento',
            name='id_operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ir.Operacao'),
        ),
    ]
